# Generated by Django 4.0.3 on 2022-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='replysSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('delete_pasword', models.CharField(max_length=25)),
                ('createdon', models.DateTimeField()),
                ('reported', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='tester',
        ),
    ]
