# Generated by Django 4.0.3 on 2022-03-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_replysschema_delete_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='threadSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('delted_password', models.CharField(max_length=25)),
                ('board', models.CharField(max_length=500)),
                ('createdon', models.DateTimeField()),
                ('bumpedon', models.DateTimeField()),
                ('reported', models.BooleanField()),
                ('replies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='look.replysschema')),
            ],
        ),
    ]
