# Generated by Django 4.0.3 on 2022-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0004_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replysschema',
            old_name='delete_pasword',
            new_name='deletepassword',
        ),
        migrations.RemoveField(
            model_name='threadschema',
            name='delted_password',
        ),
        migrations.AddField(
            model_name='threadschema',
            name='deletepassword',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
