# Generated by Django 4.0.3 on 2022-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0005_rename_delete_pasword_replysschema_deletepassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replysschema',
            old_name='deletepassword',
            new_name='delete_password',
        ),
        migrations.RenameField(
            model_name='threadschema',
            old_name='deletepassword',
            new_name='delete_password',
        ),
    ]
