# Generated by Django 4.0.3 on 2022-03-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0006_rename_deletepassword_replysschema_delete_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Text', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
