export {default as  Footer} from './Footer'
export {default as  Navbar} from './Navbar'
export {default as  Exercises} from './Exercises'
export {default as  HeroBanner} from './HeroBanner'
export {default as  SearchExercises} from './SearchExercises'
export {default as  Detail} from './Detail'
export {default as SimilarExercises} from './SimilarExercises'
export {default as BodyPart} from './BodyPart'
export {default as HorizontalScrollbar} from './HorizontalScrollbar'
export {default as ExerciseVideos} from './ExerciseVideos'
 