# Generated by Django 4.0 on 2022-07-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_options_alter_brands_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
