# Generated by Django 4.0 on 2022-07-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_brands_fields_alter_contact_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='_type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
