# Generated by Django 3.1.2 on 2022-04-13 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontend.dj_frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='React_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'React Note',
                'verbose_name_plural': 'React Notes',
            },
        ),
        migrations.CreateModel(
            name='React_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=frontend.dj_frontend.models.generate_unique_code, max_length=50, unique=True)),
                ('host', models.CharField(max_length=200, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('category', models.CharField(default='General', max_length=100)),
                ('title', models.CharField(max_length=250, null=True)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'React Room',
                'verbose_name_plural': 'React Rooms',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='React_User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=50, null=True)),
                ('middle', models.CharField(blank=True, max_length=50, null=True)),
                ('last', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('security', models.BooleanField(default=False)),
                ('sec_q1', models.CharField(blank=True, max_length=200, null=True)),
                ('sec_a1', models.CharField(blank=True, max_length=200, null=True)),
                ('sec_q2', models.CharField(blank=True, max_length=200, null=True)),
                ('sec_a2', models.CharField(blank=True, max_length=200, null=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=frontend.dj_frontend.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'React User',
                'verbose_name_plural': 'React Users',
            },
        ),
        migrations.CreateModel(
            name='React_Room_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_frontend.react_room')),
            ],
            options={
                'verbose_name': 'React Room History',
                'verbose_name_plural': 'React Room History',
            },
        ),
        migrations.AddField(
            model_name='react_room',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_frontend.react_user_data'),
        ),
    ]
