# Generated by Django 3.1.2 on 2022-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react_user_data',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
