version: "3.7"
networks:
  stockforecastnetwork: 
    driver: bridge
services:

  db:
    container_name: dbcontainer

    image: timescale/timescaledb:latest-pg14
    ports:
      - 8001:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      
      POSTGRES_DB: look
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  proxy:
    container_name: proxycontainer
    image: nginx
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./Look/proxy/Dockerfile
    volumes:
      - ./Look/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./Look/look_frontend/build:/vol/frontend
      
volumes:
  db_vol: 
  static_data:


